repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
  - id: forbid-new-submodules
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-added-large-files
  - id: check-symlinks
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
